### ISSUE TITLE
Displays a notification when the browser updates

### ISSUE THREAD

**Issue by Mossop** [bomjacob/back2close#10]
The extension displays a notification in response to runtime.onInstalled regardless of the reason. This means a notification will be displayed when the user's browser updates.

**Comment by jsmnbom** [comment]
Ooops, you are quite right, that probably shouldn't be as so... I'll try and get it fixed when I have time. Thanks a lot for the report :)

**Comment by jsmnbom** [comment]
I've decided to just remove the notification completely as of version 0.7.0 :)

**Comment by CennoxX** [comment]
@jsmnbom If you no longer use notifications, could you possibly remove the notification permission too?

**Comment by jsmnbom** [comment]
Whoops, completely forgot about that, will fix shortly :)

**Comment by jsmnbom** [comment]
Fixed in 0.7.1 :)
