### ISSUE TITLE
Sometimes when opening a new tab I'll see the address of the link clicked in the tab instead of the page title

### ISSUE THREAD

**Issue by Mossop** [bomjacob/back2close#11]
I commonly see this when opening tabs from links in Slack for example. I'll click a link, a new tab will open and eventually I see a "slack-redir.net" url in the tab even though the page has redirected to a different url and obviously has a different page title.

**Comment by jsmnbom** [comment]
Do you have any public urls that I can test this on?

**Comment by BreadYogurt** [comment]
This happens to me as well, most notably on Reddit.

**Comment by jsmnbom** [comment]
@Mossop and @BreadYogurt is this fixed on the newest version 0.7.0 of the addon?
I changed some things, that should make how titles are handled work better.

**Comment by jsmnbom** [comment]
Assuming the bug has been fixed since I've heard nothing more.
