### ISSUE TITLE
Simple Feature Suggestion

### ISSUE THREAD

**Issue by markran** [bomjacob/back2close#12]
I love this add-on! It would be AMAZING if you could add the matching inverse behavior of "Back2Close" with a "Forward to Undo Close Tab" option. Undo Close Tab is already supported by FF with the shortcut (CTRL+Shift+T). If there are no more Forward addresses in the buffer, then do the same thing as (CTRL+Shift+T) ELSE if there are forward addresses just do a normal Forward. That would make the behavior of the add-on pretty much orthogonal. 

It would also be wonderful if you could include a keyboard shortcut to that function (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values)

Thanks and have a great day!

**Comment by jsmnbom** [comment]
This unfortunately won't be possible to implement. The way I currently control the browsers history is using the HTML5 history API in the actual tab:
1) This means that all tabs would need to update and know what the recently closed tab is
2) The history API doesn't support adding history entries in the future as far as I'm aware.

If firefox ever ends up supporting a proper history manipulation API from a webextension context, then this might be possible, but for now it simply isn't. Sorry about that.
