### ISSUE TITLE
Not Working for mozilla.org URLs?

### ISSUE THREAD

**Issue by OliverPearmain** [bomjacob/back2close#15]
Not sure if its just me but the extension does not seem to work if the first URL in the tabs history is a mozilla.org address. When you go attempt back the tab does not close.

This probably wouldn't be too much of an issue except that because users have just installed the plugin from a mozilla.org extension page, the first thing they are likely to try is opening some arbitrary link from that page which chances are will be a mozilla.org link.  And so on first attempt is appears to new users that the extension doesn't work. This was certainly my experience, and I only later discovered, by chance that it was actually working.

**Comment by CennoxX** [comment]
It's a feature, not a bug. This is a Firefox constraint: addons don't work on the firefox addon pages for security reasons.

**Comment by OliverPearmain** [comment]
All good, appreciate the reply, I'll close the issue.
