### ISSUE TITLE
"Load on all tabs" has to be unchecked then checked again, after first install

### ISSUE THREAD

**Issue by ElhemEnohpi** [bomjacob/back2close#4]
Hi, thanks for this extension! I used "Back to close" a long time ago but it stopped working for me, so it's great to have it back again.

Just one thing, after I installed it, tabs opened from a New Tab wouldn't close, only from "Open in a new tab", even though "Load on all tabs" is checked by default. After a while, I figured out I had to uncheck it, then check it again.

**Comment by jsmnbom** [comment]
Hmm.. thanks a lot for this report! :D I'll look into what could be causing these issues. Note that I'm currently very busy, so progress might be a bit slow :)

**Comment by jsmnbom** [comment]
@ElhemEnohpi Could you try with version v0.6.0? It should be public on AMO in a few minutes :)

**Comment by ElhemEnohpi** [comment]
Yes, it seems to be fixed in the new version, thanks!
