### ISSUE TITLE
Page titles may be displayed as the URL of the website instead of the actual title

### ISSUE THREAD

**Issue by ghost** [bomjacob/back2close#5]
When new tabs are opened, sometimes the title of the page will be displayed as the address of the page you're on, instead of the actual page title.

I was able to reproduce this bug on a blank profile of the latest version of Firefox (57.0.2 64-bit) with Windows 7 and Arch Linux (both 64-bit). I've attached a screenshot and video link showing this bug. The video also shows the "close tab" bug. Since this is the only back to close addon out there now, I'll try to help where I can.

![Screenshot](https://user-images.githubusercontent.com/3119419/34235863-4aa6456a-e5a9-11e7-9444-bd5b7c2ab07f.png)

[WebM](https://drive.google.com/file/d/1qD92g4cM3zNBblOgrUd40dbsjGirfhEX/view)

**Comment by jsmnbom** [comment]
v0.6.0 should fix this issue :D 
It should go public on AMO in just a few minutes.
Thank you so much for the very detailed report :)
