### ISSUE TITLE
Issues with Firefox earlier than 57, addon can't be used.

### ISSUE THREAD

**Issue by ElhemEnohpi** [bomjacob/back2close#6]
back2close is unfortunately not working properly, and can't be used, with Firefox 52 ESR, FF 56,  Waterfox, etc. There are two issues I've found:

Issue 1: When "Load on all tabs" is checked, the first new tab opened in a window works as expected, but the second and subsequent ones don't. 

Steps to reproduce:
1. Create a new profile using Firefox 52.5.2 - 56.0.2, and install back2close.
2. Uncheck then re-check the "Load on all tabs" preference box, to be sure it's set.
3. Open a new tab with the New Tab button or keyboard shortcut; the New Tab page opens.
4. Go to a web page by entering a URL, search, or  clicking on a tile.
5. Switch to the new tab.
_Note that the "back" button indicates it has history, and right clicking on it shows two entries, as expected._
6. Repeat steps 3-5.
_Now note that the new tab's "back" button does not show any history. I expected it to be the same as the first tab._
7. Switch to the first new tab, and press the "back" button.
_Note that the tab closes as expected._
8. Switch to the second new tab, and press the "back" button.
_Note that nothing happens. I expected it to close._
9. Click any link on the second new tab.
_Note that the "back" button now shows three history entries, and the extra one is prior to the current page._
10. Press the "back" button.
_Note that the tab closes. I expected it to go back to the previous page._

Issue 2: When "Load on all tabs" is not checked, the addon does nothing at all.

Steps to reproduce:
1. Create a new profile using Firefox 52.5.2 - 56.0.2, and install back2close.
2. Check and then uncheck the "Load on all tabs" preference box, to be sure it's cleared.
3. Open a new tab and go to a URL, eg. github.com.
4. Right-click on any link, and choose "Open link in new tab". Alternatively, click on any link with target="_blank" that opens a new page/tab.
_Note that the new tab has no history, and will not close via the "back" button._

**Comment by jsmnbom** [comment]
Hmm.. it is quite possible that I'm using 57+ features.. I'll have to check that, thanks for the report in any case :D

**Comment by ElhemEnohpi** [comment]
Ok, thanks for looking into it. I'm enjoying using Back to Close in Firefox Quantum, but my main browser is still Firefox 56, and will be Waterfox soon, probably for the next year or more. It would be great if I could use it there too!

**Comment by ElhemEnohpi** [comment]
I figured out a work-around for issue 1 above. Use Classic Theme Restorer to set "custom new tab page URL" to "about:blank" (or whatever, just not "about:newtab"). After that it just works.

It doesn't help with issue 2 though.
