### ISSUE TITLE
[request] Supress extra History entries

### ISSUE THREAD

**Issue by ElhemEnohpi** [bomjacob/back2close#8]
Since installing Back To Close, I've noticed many "Close tab" entries in the "Show All History" window. Would it be possible to supress them? I tried unchecking "Show "Close tab" in history", but I still get duplicate entries for the URL, but ending with a `#`.

**Comment by jsmnbom** [comment]
Hmm, that is a very good question actually. The code relies on sending you to a psudo-new-page kinda thing, so it knows that it already ran. I'll look into what i can do when I get time though. Thanks a lot for the request :D

**Comment by ElhemEnohpi** [comment]
By now I have literally thousands of these "Close tab" entries in my history, with the URL ending in `#`. I did a search and deleted them - which took over an hour - but it looks like sometimes they don't get the "Close tab" name, but the name of the page instead. So the history database is still unnecessarily bloated by these entries.

Just hoping you might find some time to add the feature to delete the psuedo-page from the history, when the tab is closed. Thanks!

**Comment by jsmnbom** [comment]
This is quite possibly fixed in version 0.7.0 of the addon. If not, please do open the issue again :D

**Comment by ElhemEnohpi** [comment]
Seems to be fixed, thanks!
